[features]
seeds = false
skip-lint = false
[programs.devnet]
notes_system = "Cm1A1eSrCVbKmpcM944cMgDMbWBsDq9c1tyD1sKwJD1G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/MainAccount.ts"
sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Sell.ts"
check = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Check.ts"
exchange = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Exchange.ts"